// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WepApp2.Models;

#nullable disable

namespace WepApp2.Migrations
{
    [DbContext(typeof(Dbgroup2Context))]
    [Migration("20250718094307_RemoveDeviceRelationFromService")]
    partial class RemoveDeviceRelationFromService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WepApp2.Models.BookingDevice", b =>
                {
                    b.Property<int>("BookingDeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingDeviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDeviceID"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("BookingDeviceID")
                        .HasName("PK__BookingD__6263A24908874900");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingDevices");
                });

            modelBuilder.Entity("WepApp2.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .HasColumnType("int")
                        .HasColumnName("ConsultationID");

                    b.Property<TimeOnly>("AvailableTimes")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ConsultationDate")
                        .HasColumnType("date");

                    b.Property<string>("ConsultationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsultationMajorId")
                        .HasColumnType("int")
                        .HasColumnName("ConsultationMajorID");

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.HasKey("ConsultationID")
                        .HasName("PK__Consulta__5D014A78858DB694");

                    b.HasIndex("ConsultationMajorId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("WepApp2.Models.ConsultationMajor", b =>
                {
                    b.Property<int>("ConsultationMajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsultationMajorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationMajorID"));

                    b.Property<string>("ConsultationDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ConsultationMajorID")
                        .HasName("PK__Consulta__C757E54FDAE44A16");

                    b.ToTable("ConsultationMajors");
                });

            modelBuilder.Entity("WepApp2.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseField")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PresenterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.HasKey("CourseID")
                        .HasName("PK__Courses__C92D7187281C46B9");

                    b.HasIndex("ServiceId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WepApp2.Models.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int")
                        .HasColumnName("TechnologyID");

                    b.HasKey("DeviceID")
                        .HasName("PK__Devices__49E12331AE3549DC");

                    b.HasIndex("TechnologyId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WepApp2.Models.DeviceLoan", b =>
                {
                    b.Property<int>("DeviceLoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeviceLoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceLoanID"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("DeviceLoanID")
                        .HasName("PK__DeviceLo__385CB179A85FB7C9");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DeviceLoans");
                });

            modelBuilder.Entity("WepApp2.Models.LabVisit", b =>
                {
                    b.Property<int>("LabVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabVisitID"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfVisitors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitDetailsId")
                        .HasColumnType("int")
                        .HasColumnName("VisitDetailsID");

                    b.HasKey("LabVisitID")
                        .HasName("PK__LabVisit__DDA12342E18829A7");

                    b.HasIndex("RequestId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("VisitDetailsId");

                    b.ToTable("LabVisits");
                });

            modelBuilder.Entity("WepApp2.Models.Request", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<string>("AdminStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("DeviceID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int?>("SupervisorAssigned")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("بإنتظار إسناد المشرف");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RequestID")
                        .HasName("PK__Requests__33A8519A66055425");

                    b.HasIndex("CourseID");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("WepApp2.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ServiceID")
                        .HasName("PK__Services__C51BB0EAF5B6E17D");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WepApp2.Models.Technology", b =>
                {
                    b.Property<int>("TechnologyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TechnologyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnologyID"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TechnologyDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TechnologyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TechnologyID")
                        .HasName("PK__Technolo__705701783492A34E");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("WepApp2.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastLogIn")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserPassWord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserID")
                        .HasName("PK__Users__1788CCAC15D188DC");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Users__85FB4E38F82DB5BA")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534374EE266")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__C9F2845697958F24")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WepApp2.Models.VisitsDetail", b =>
                {
                    b.Property<int>("VisitDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VisitDetailsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitDetailsID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("visitType");

                    b.HasKey("VisitDetailsID")
                        .HasName("PK__VisitsDe__BCA58B13ED325902");

                    b.ToTable("VisitsDetails");
                });

            modelBuilder.Entity("WepApp2.Models.BookingDevice", b =>
                {
                    b.HasOne("WepApp2.Models.Device", "Device")
                        .WithMany("BookingDevices")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK_BookingDevices_Devices");

                    b.HasOne("WepApp2.Models.Request", "Request")
                        .WithMany("BookingDevices")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_BookingDevices_Requests");

                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("BookingDevices")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_BookingDevices_Services");

                    b.Navigation("Device");

                    b.Navigation("Request");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WepApp2.Models.Consultation", b =>
                {
                    b.HasOne("WepApp2.Models.ConsultationMajor", "ConsultationMajor")
                        .WithMany("Consultations")
                        .HasForeignKey("ConsultationMajorId")
                        .IsRequired()
                        .HasConstraintName("FK_Consultations_ConsultationMajors");

                    b.HasOne("WepApp2.Models.Request", "Request")
                        .WithMany("Consultations")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_Consultations_Request");

                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("Consultations")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_Consultations_Services");

                    b.Navigation("ConsultationMajor");

                    b.Navigation("Request");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WepApp2.Models.Course", b =>
                {
                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("Courses")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_Courses_Services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WepApp2.Models.Device", b =>
                {
                    b.HasOne("WepApp2.Models.Technology", "Technology")
                        .WithMany("Devices")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Devices_Technologies");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("WepApp2.Models.DeviceLoan", b =>
                {
                    b.HasOne("WepApp2.Models.Device", "Device")
                        .WithMany("DeviceLoans")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK_DeviceLoans_Devices");

                    b.HasOne("WepApp2.Models.Request", "Request")
                        .WithMany("DeviceLoans")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_DeviceLoans_Requests");

                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("DeviceLoans")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_DeviceLoans_Services");

                    b.Navigation("Device");

                    b.Navigation("Request");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WepApp2.Models.LabVisit", b =>
                {
                    b.HasOne("WepApp2.Models.Request", "Request")
                        .WithMany("LabVisits")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_LabVisits_Requests");

                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("LabVisits")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_LabVisits_Services");

                    b.HasOne("WepApp2.Models.VisitsDetail", "VisitDetails")
                        .WithMany("LabVisits")
                        .HasForeignKey("VisitDetailsId")
                        .HasConstraintName("FK_LabVisits_VisitsDetails");

                    b.Navigation("Request");

                    b.Navigation("Service");

                    b.Navigation("VisitDetails");
                });

            modelBuilder.Entity("WepApp2.Models.Request", b =>
                {
                    b.HasOne("WepApp2.Models.Course", "Course")
                        .WithMany("Requests")
                        .HasForeignKey("CourseID")
                        .HasConstraintName("FK_Request_Courses");

                    b.HasOne("WepApp2.Models.Device", "Device")
                        .WithMany("Requests")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK_Request_Devices");

                    b.HasOne("WepApp2.Models.Service", "Service")
                        .WithMany("Requests")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Request_Services");

                    b.HasOne("WepApp2.Models.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Request_Users");

                    b.Navigation("Course");

                    b.Navigation("Device");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WepApp2.Models.ConsultationMajor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("WepApp2.Models.Course", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WepApp2.Models.Device", b =>
                {
                    b.Navigation("BookingDevices");

                    b.Navigation("DeviceLoans");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WepApp2.Models.Request", b =>
                {
                    b.Navigation("BookingDevices");

                    b.Navigation("Consultations");

                    b.Navigation("DeviceLoans");

                    b.Navigation("LabVisits");
                });

            modelBuilder.Entity("WepApp2.Models.Service", b =>
                {
                    b.Navigation("BookingDevices");

                    b.Navigation("Consultations");

                    b.Navigation("Courses");

                    b.Navigation("DeviceLoans");

                    b.Navigation("LabVisits");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WepApp2.Models.Technology", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("WepApp2.Models.User", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WepApp2.Models.VisitsDetail", b =>
                {
                    b.Navigation("LabVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
